# Generated by Django 3.0.5 on 2021-05-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('sid', models.CharField(blank=True, default=None, max_length=10)),
                ('service', models.CharField(blank=True, default=None, max_length=10)),
                ('type', models.CharField(choices=[('oracle', 'oracle'), ('postgres', 'postgres')], max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
