# Generated by Django 3.0.5 on 2021-05-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBCompare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dst_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_db', to='dbs.DBInstance')),
                ('src_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_db', to='dbs.DBInstance')),
            ],
        ),
        migrations.CreateModel(
            name='DBTableCompare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=400)),
                ('src_row_count', models.IntegerField(default=0, null=True)),
                ('dst_row_count', models.IntegerField(default=0, null=True)),
                ('mismatch_in_cols_count', models.BooleanField(default=False)),
                ('compare_dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_db_d_db', to='dbs.DBCompare')),
            ],
        ),
        migrations.CreateModel(
            name='DBTableColumnCompare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('oracle', 'oracle'), ('postgres', 'postgres')], max_length=100)),
                ('column_name', models.CharField(max_length=100)),
                ('datatype', models.CharField(max_length=100)),
                ('compare_dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s1_db_d1_db', to='dbs.DBCompare')),
            ],
        ),
        migrations.CreateModel(
            name='DBStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=400)),
                ('total_rows_inserted', models.IntegerField(default=0, null=True)),
                ('total_rows_errors', models.IntegerField(default=0, null=True)),
                ('compare_dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2_db_d2_db', to='dbs.DBCompare')),
            ],
        ),
    ]
