# Generated by Django 3.0.5 on 2021-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SYSettings',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('settings', models.CharField(max_length=400)),
            ],
        ),
    ]
