# Generated by Django 3.0.5 on 2021-05-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_dbtablecompare'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTableColumnCompare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('oracle', 'oracle'), ('postgres', 'postgres')], max_length=100)),
                ('column_name', models.CharField(max_length=100)),
                ('datatype', models.CharField(max_length=100)),
                ('dst_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_db_column', to='dbs.DBInstance')),
                ('src_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_db_column', to='dbs.DBInstance')),
            ],
        ),
    ]
