# Generated by Django 3.0.5 on 2021-05-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0003_sysettings_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTableCompare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=400)),
                ('src_row_count', models.IntegerField(default=0, null=True)),
                ('dst_row_count', models.IntegerField(default=0, null=True)),
                ('mismatch_in_cols_count', models.BooleanField(default=False)),
                ('dst_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_db', to='dbs.DBInstance')),
                ('src_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_db', to='dbs.DBInstance')),
            ],
        ),
    ]
