# Generated by Django 3.0.5 on 2021-05-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0003_auto_20210511_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbinstance',
            options={'ordering': ('host', 'name', 'sid', 'service')},
        ),
    ]
