# Generated by Django 3.0.5 on 2021-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0004_auto_20210512_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtablecompare',
            name='geom',
            field=models.BooleanField(default=False),
        ),
    ]
