# Generated by Django 3.0.5 on 2021-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0005_dbtablecompare_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtablecolumncompare',
            name='precision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
