# Generated by Django 3.0.5 on 2021-05-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0007_auto_20210515_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbcompare',
            options={'permissions': [('can_compare_db', 'User can compare DB instance')]},
        ),
        migrations.AlterModelOptions(
            name='dbinstance',
            options={'ordering': (['host', 'name', 'sid', 'service'],), 'permissions': [('can_disable_triggers', 'User can disable triggers'), ('can_enable_triggers', 'User can enable triggers'), ('can_bulk_import', 'User can do bulk import'), ('can_copy_table_content', 'User can do table copy')]},
        ),
    ]
