# Generated by Django 3.0.5 on 2021-05-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0008_auto_20210517_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbinstance',
            options={'ordering': ('host', 'name', 'sid', 'service'), 'permissions': [('can_disable_triggers', 'User can disable triggers'), ('can_enable_triggers', 'User can enable triggers'), ('can_bulk_import', 'User can do bulk import'), ('can_copy_table_content', 'User can do table copy'), ('can_truncate_table_content', 'User can truncate table content')]},
        ),
    ]
