# Generated by Django 3.0.5 on 2021-05-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0009_auto_20210517_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBObjectCompare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=400)),
                ('src_exists', models.BooleanField(default=False, null=True)),
                ('dst_exists', models.BooleanField(default=False, null=True)),
                ('type', models.CharField(choices=[('view', 'view'), ('sequence', 'sequence'), ('trigger', 'trigger')], max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('table_name',),
            },
        ),
        migrations.AddIndex(
            model_name='dbcompare',
            index=models.Index(fields=['src_db', 'dst_db'], name='dbs_dbcompa_src_db__c26fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='dbtablecolumncompare',
            index=models.Index(fields=['table_name', 'compare_dbs', 'column_name', 'added_on'], name='dbs_dbtable_table_n_dcaab6_idx'),
        ),
        migrations.AddIndex(
            model_name='dbtablecompare',
            index=models.Index(fields=['table_name', 'compare_dbs', 'added_on'], name='dbs_dbtable_table_n_4e3234_idx'),
        ),
        migrations.AddField(
            model_name='dbobjectcompare',
            name='compare_dbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_db_d3_db', to='dbs.DBCompare'),
        ),
    ]
