# Generated by Django 3.0.5 on 2021-06-10 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0011_auto_20210610_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbobjectfkcompare',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
