# Generated by Django 3.0.5 on 2021-06-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0012_dbobjectfkcompare_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbobjectfkcompare',
            name='dst_exists',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dbobjectfkcompare',
            name='src_exists',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
