# Generated by Django 3.0.5 on 2021-07-07 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0013_auto_20210627_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcompare',
            name='last_compared',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbinstance',
            name='service',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbinstance',
            name='sid',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dbobjectcompare',
            name='type',
            field=models.CharField(choices=[('view', 'view'), ('sequence', 'sequence'), ('trigger', 'trigger'), ('index', 'index')], max_length=100),
        ),
    ]
