# Generated by Django 3.0.5 on 2021-07-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0014_auto_20210706_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtablecompare',
            name='module_id',
            field=models.BooleanField(default=False),
        ),
    ]
