# Generated by Django 3.0.5 on 2021-08-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0015_dbtablecompare_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtablecolumncompare',
            name='is_ui',
            field=models.BooleanField(default=False),
        ),
    ]
