# Generated by Django 3.0.5 on 2021-08-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0016_dbtablecolumncompare_is_ui'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBCompareDBResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_compared', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('compare_dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_c_db_d_c_db', to='dbs.DBCompare')),
            ],
        ),
        migrations.AddIndex(
            model_name='dbcomparedbresults',
            index=models.Index(fields=['compare_dbs', 'last_compared', 'status'], name='dbs_dbcompa_compare_bd845a_idx'),
        ),
    ]
