# Generated by Django 3.1.13 on 2021-11-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0019_dbtablecompare_last_compared_file_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtablecolumncompare',
            name='src_dst',
            field=models.CharField(blank=True, choices=[('src', 'src'), ('dst', 'dst')], max_length=10, null=True),
        ),
    ]
