# Generated by Django 3.1.13 on 2021-11-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0020_dbtablecolumncompare_src_dst'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTableCompareTokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='dbtablecolumncompare',
            name='dbs_dbtable_table_n_dcaab6_idx',
        ),
        migrations.AddIndex(
            model_name='dbtablecolumncompare',
            index=models.Index(fields=['table_name', 'compare_dbs', 'column_name', 'added_on', 'src_dst'], name='dbs_dbtable_table_n_7f7215_idx'),
        ),
    ]
