version: '3.6'
services:
  redis-server:
    image: redis:latest
    restart: always
    container_name: redis_for_diablo
    ports:
      - 127.0.0.1:6379:6379
    depends_on:
      - diablo
  diablo:
    image: postgres:12.3
    restart: always
    container_name: Diablo
    environment:
      POSTGRES_PASSWORD: diablo
      POSTGRES_USER: diablo
      POSTGRES_DB: diablo
    ports:
      - 127.0.0.1:6432:5432
    volumes:
      - ./volumes:/var/lib/postgresql/data:cached
