version: '3.6'
services:
  diablo-redis:
    image: redis:latest
    restart: always
    container_name: diablo-redis
    ports:
      - 6379:6379
    depends_on:
      - diablo-db
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  diablo-db:
    image: postgres:12.3
    restart: always
    container_name: diablo-db
    environment:
      POSTGRES_PASSWORD: diablo
      POSTGRES_USER: diablo
      POSTGRES_DB: diablo
    ports:
      - 6432:5432
    volumes:
      - ./volumes:/var/lib/postgresql/data:cached
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "diablo", "-U", "diablo" ]
      interval: 10s
      timeout: 3s
      retries: 3