# Generated by Django 3.0.5 on 2021-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysetting',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
