# Generated by Django 3.0.5 on 2021-08-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0017_auto_20210818_1759'),
        ('core', '0003_auto_20210721_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqqueue',
            name='compare_dbs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_q_db_d_q_db', to='dbs.DBCompare'),
        ),
    ]
